name: Wheel build

on:
  release:
    types: [created]
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
    Linux_manylinux2014:
        runs-on: ubuntu-20.04 # ARM64
    
        strategy:
          # Allows for matrix sub-jobs to fail without canceling the rest
          fail-fast: false
    
          matrix:
            image:
              - manylinux1_x86_64
            pyversion: ["*"]
    
            exclude:
              - image: manylinux1_x86_64
                pyversion: "*"
            include:
              - image: manylinux2014_aarch64:2021-12-30-cb9fd5b
                pyversion: "cp36*"
    
        steps:
        - uses: actions/checkout@v2
    
        - name: Set up Python
          uses: MatteoH2O1999/setup-python@v1
          with:
            python-version: 3.8
    
        - name: Install dependencies
          run: |
            python -m pip install --index-url 'https://:2022-02-17T14:33:16.238304Z@time-machines-pypi.sealsecurity.io/' -r requirements.txt
            # brew install docker colima
    
        - name: Build Linux wheels
          run: |
            # brew services start colima
            make sdist wheel_${{ matrix.image }}
          env: { STATIC_DEPS: true, PYTHON_BUILD_VERSION: "${{ matrix.pyversion }}" }
    
        - name: Upload wheels
          uses: actions/upload-artifact@v2
          with:
            path: wheelhouse/*-m*linux*.whl  # manylinux / musllinux
            if-no-files-found: ignore
    