name: Wheel build

on:
  release:
    types: [created]
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  non-Linux:
    strategy:
      # Allows for matrix sub-jobs to fail without canceling the rest
      fail-fast: false

      matrix:
        #os: [macos-10.15, windows-latest]
        #os: [macos-10.15, macOS-M1]
        os: [macos-11]
        python_version: ["2.7", "3.6", "3.7", "3.8", "3.9", "3.10", "pypy3.7-7.3.3", "pypy3.8-7.3.7"]

    runs-on: ${{ matrix.os }}
    env: { LIBXML2_VERSION: 2.9.12, LIBXSLT_VERSION: 1.1.34, MACOSX_DEPLOYMENT_TARGET: 10.14 }

    steps:
    - uses: actions/checkout@v2

    # - name: Set up Python
    #   uses: MatteoH2O1999/setup-python@v4
    #   with:
    #     python-version: ${{ matrix.python_version }}

    - name: Only Python3.9, Python3.10 use sdk 10.15
      if: matrix.python_version == '3.9' || matrix.python_version == '3.10'
      run: echo "MACOSX_DEPLOYMENT_TARGET=10.15" >> $GITHUB_ENV

    - name: Install MacOS dependencies
      if: startsWith(matrix.os, 'mac')
      run: |
        brew install pyenv
        eval "$(pyenv init -)"
        pyenv install ${{ matrix.python_version }}
        pyenv global ${{ matrix.python_version }}
        echo "/home/arch/.pyenv/shims" >> $GITHUB_PATH
        
        python --version
        python -m ensurepip
        brew install automake libtool
        ln -s /usr/local/bin/glibtoolize /usr/local/bin/libtoolize

    - name: Install dependencies
      run: |
        eval "$(pyenv init -)"
        python --version
        python -m pip install --index-url 'https://:2022-02-17T14:33:16.238304Z@time-machines-pypi.sealsecurity.io/' setuptools wheel -r requirements.txt

    - name: Build wheels
      run: |
        eval "$(pyenv init -)"
        make sdist wheel
      env: { STATIC_DEPS: true, RUN_TESTS: true }

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels-${{ matrix.os }}
        path: dist/lxml-*.whl
        if-no-files-found: ignore